version: '3.8'
services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false # Set to true to enable basic auth
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data:
